### ISSUE TITLE
It's better to use the "unshare" binary provided by the package in the arch-chroot

### ISSUE THREAD

**Issue by Kimi-Arthur** [falconindy/arch-install-scripts#22]
For my system, the following won't work since my "unshare" binary in the system doesn't understand the "--fork" argument. (Actually even the "--pid" argument could not be understood)

    SHELL=/bin/sh unshare --fork --pid chroot "$chrootdir" "$@"

So I think it's better to make the last line look like the following (which works on my system):

    SHELL=/bin/sh $chrootdir/bin/unshare --fork --pid chroot "$chrootdir" "$@"

**Comment by falconindy** [comment]
I'd much rather just put a minimum version requirement on util-linux for the host. In this case, it means requiring v2.24 which was released in October 2013 -- I don't think this is unreasonable.

Executing commands out of the chroot means that you still dynamically load libraries from the host system. In this case, unshare is quite simple, but you can still run into symbol version mismatches (as glibc does not guarantee forwards compat). If dynamic library dependencies were introduced in future versions of unshare, this could manifest itself as similar failures to what you see now.
