### ISSUE TITLE
udev mount error

### ISSUE THREAD

**Issue by ghost** [falconindy/arch-install-scripts#26]
Trying to get arch-chroot too run mkinitcpio (for installed kernel) but am getting an error 

udev is already mounted on /mnt/dev

lsof is not really much help and I cannot unmount /mnt/dev....

Not really sure what would be causing the problem, why does arch-chroot mount udev?

**Comment by falconindy** [comment]
Without knowing what steps you took to get to this error, I can't really help you. What do you mean you cannot unmount /mnt/dev.... ?

**Comment by mrgreen3** [comment]
If you try to umount /mnt/dev or udev I get device busy. Am running normal arch-install-scripts (a normal arch install) to a virtual machine. Has always thought you only need to mount /dev/proc/sys (and copy over resolv.conf for network. Just curious as too udev....

As you say you cannot really help without more information, was just interested as too why udev is mounted... (can google that!)

Thanks

**Comment by falconindy** [comment]
If you are using arch-chroot, you should not be mounting anything at all.
