### ISSUE TITLE
/usr/bin/pacman: error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mickours** [falconindy/arch-install-scripts#30]
The script fails while trying to run pacman for the first time with this error

**Comment by falconindy** [comment]
"The script"? I assume you mean pacstrap? Under what conditions? Could you provide specific steps to reproduce this? My guess is your system is out of date given that pacman depends on curl depends on libpsl ...

**Comment by mickours** [comment]
Sorry for that, I was exhausted yesterday so I was a bit lazy ;)

It seems to be a transient problem due to the fact that I am behind a proxy. I retried today and It also fails but while trying to update pacman repository.
I just switch to another proxy and it works.

Sorry again for the noise...
